// Fetches the BrickLink numbers the trading cards use to decide how rare a figure is,
// and writes them to data/card-stats.yaml. Run it now and then; the site never
// calls BrickLink, it only reads the file.
//
//   node scripts/fetchCardStats.js                 fetch every figure not in the file yet
//   node scripts/fetchCardStats.js --limit 20      only the next 20
//   node scripts/fetchCardStats.js --only sw1273,sh0151
//   node scripts/fetchCardStats.js --refresh       redo every figure, not just the missing ones
//
// From each figure's catalog page it reads how many sets it appears in, how many lots
// are for sale right now, and the year it came out. The price guide would say more,
// but BrickLink answers it with a bot challenge instead of a page, so it is not used.
//
// It is slow and polite on purpose (one request at a time, a pause between them),
// saves as it goes so an interrupted run loses nothing, and STOPS at the first sign
// of blocking (429, 403, a challenge page) or after three failures in a row, rather
// than pushing on. Run it again later and it carries on where it left off.
import fs from "fs";
import path from "path";
import { dump, load } from "js-yaml";
import { DATA_DIR, localImageIds } from "./lib/collection.js";

const STATS_FILE = path.join(DATA_DIR, "card-stats.yaml");

const USER_AGENT =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0 Safari/537.36";
const PAUSE_MS = 1500; // plus up to another 700, so the requests are not evenly spaced
const SAVE_EVERY = 10;
const MAX_FAILURES_IN_A_ROW = 3;

const args = process.argv.slice(2);
const flag = name => args.includes(`--${name}`);
const value = name => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : null;
};

function readStats() {
  if (!fs.existsSync(STATS_FILE)) return {};
  return load(fs.readFileSync(STATS_FILE, "utf8")) ?? {};
}

function writeStats(stats) {
  const sorted = Object.fromEntries(Object.entries(stats).sort(([a], [b]) => a.localeCompare(b)));
  const header = `# BrickLink numbers for the trading cards, one line per figure. Generated by
# \`npm run card-stats\`; do not edit by hand, since the next run would replace it.
#
#   sets   how many sets the figure appears in
#   lots   how many lots were for sale when it was fetched
#   year   the year it was first released
#   date   when this line was fetched
#
# A figure missing here (or with a null) counts as unknown, and is treated as
# middling rather than rare or common.
`;
  fs.writeFileSync(STATS_FILE, header + dump(sorted, { flowLevel: 1, lineWidth: 200 }), "utf8");
}

// Something we should not push past: stop the whole run
class Blocked extends Error {}

async function fetchPage(id) {
  const url = `https://www.bricklink.com/v2/catalog/catalogitem.page?M=${id}`;
  const res = await fetch(url, { headers: { "User-Agent": USER_AGENT }, signal: AbortSignal.timeout(30000) });
  if ([403, 429, 503].includes(res.status)) throw new Blocked(`BrickLink answered ${res.status}`);
  if (res.status === 404) return null;
  if (!res.ok) throw new Error(`BrickLink answered ${res.status}`);
  const html = await res.text();
  if (/just a moment|captcha|access denied|are you a robot/i.test(html) && !html.includes("yearReleasedSec")) {
    throw new Blocked("BrickLink sent a challenge page");
  }
  return html;
}

function parse(html) {
  const text = html
    .replace(/<script[\s\S]*?<\/script>|<style[\s\S]*?<\/style>/gi, " ")
    .replace(/<[^>]+>/g, " ")
    .replace(/&nbsp;/g, " ")
    .replace(/\s+/g, " ");

  const number = pattern => {
    const match = text.match(pattern);
    return match ? Number(match[1].replace(/,/g, "")) : null;
  };

  const sets = number(/Item Appears In ([\d,]+) Sets?/i);
  const lots = number(/([\d,]+) Lots? For Sale/i);
  const year = number(/Years? Released:\s*(\d{4})/i) ?? number(/id="yearReleasedSec">(\d{4})</i);
  return { sets, lots, year };
}

const sleep = ms => new Promise(resolve => setTimeout(resolve, ms));

async function main() {
  const stats = readStats();
  const only = value("only")?.split(",").map(id => id.trim().toLowerCase());
  const limit = Number(value("limit")) || Infinity;

  let queue = only ?? localImageIds();
  if (!flag("refresh") && !only) queue = queue.filter(id => !(id in stats));
  queue = queue.slice(0, limit);

  console.log(`${queue.length} figure${queue.length === 1 ? "" : "s"} to fetch (${Object.keys(stats).length} already on file).`);

  let done = 0;
  let failuresInARow = 0;
  const date = new Date().toISOString().slice(0, 10);

  const save = () => writeStats(stats);
  process.on("SIGINT", () => {
    save();
    console.log("\nInterrupted; progress saved.");
    process.exit(130);
  });

  try {
    for (const id of queue) {
      try {
        const html = await fetchPage(id);
        if (html === null) {
          console.log(`${id}: no such page on BrickLink, skipped`);
        } else {
          const { sets, lots, year } = parse(html);
          stats[id] = { sets, lots, year, date };
          console.log(`${id}: ${sets ?? "?"} sets, ${lots ?? "?"} lots, ${year ?? "?"}`);
          done++;
        }
        failuresInARow = 0;
      } catch (error) {
        if (error instanceof Blocked) {
          console.log(`${id}: ${error.message}. Stopping here; try again later.`);
          break;
        }
        failuresInARow++;
        console.log(`${id}: failed (${error.message})`);
        if (failuresInARow >= MAX_FAILURES_IN_A_ROW) {
          console.log(`${MAX_FAILURES_IN_A_ROW} failures in a row. Stopping here; try again later.`);
          break;
        }
      }
      if (done > 0 && done % SAVE_EVERY === 0) save();
      await sleep(PAUSE_MS + Math.random() * 700);
    }
  } finally {
    save();
  }

  const left = localImageIds().filter(id => !(id in stats)).length;
  console.log(`Fetched ${done}. ${Object.keys(stats).length} on file, ${left} still missing.`);
}

main();
